### ISSUE TITLE
After creating Fuse project in Lab01, should be change perspective?

### ISSUE THREAD

**Issue by hguerrero** [jbossdemocentral/fuse-introlab#11]
After finishing creating the new Fuse project in Lab01 do we need to change perspective?
![screenshot from 2017-07-20 18-27-58](https://user-images.githubusercontent.com/1001939/28428272-83889bc8-6d3e-11e7-94bb-fd8e063fdad2.png)

**Comment by weimeilin79** [comment]
Added instruction!
