### ISSUE TITLE
Lab 01 - maven build windows is not poping up

### ISSUE THREAD

**Issue by hguerrero** [jbossdemocentral/fuse-introlab#12]
In the instructions of lab01 to popup the maven build window the correct option to select is the one with the three points (...).

**Comment by weimeilin79** [comment]
Can you elaborate on that?

**Comment by hguerrero** [comment]
https://github.com/hguerrero/fuse-introlab/raw/master/lab01/img/14-mavenrun.png

In this image there are two options to run maven: one that ends with "..." and the other withour the dots. The option with the dots is the one that pops up the maven dialog. The other does not.

**Comment by weimeilin79** [comment]
OK. Got it!
