### ISSUE TITLE
route name for lab01 and lab02

### ISSUE THREAD

**Issue by hguerrero** [jbossdemocentral/fuse-introlab#13]
In the step to add the REST dsl to the camel route if people cut and paste there is a duplicated route tag as the lab01 names it "customer" and the lab02 snippet references it as "customers". Also if they cut and paste the text it will end with two route tags (the previous already there and the pasted one).

    <camelContext id="camel" xmlns="http://camel.apache.org/schema/spring">
       <restConfiguration apiContextPath="api-docs" bindingMode="json"
            component="servlet" contextPath="/myfuselab">
            <apiProperty key="cors" value="true"/>
            <apiProperty key="api.title" value="My First Camel API Lab"/>
            <apiProperty key="api.version" value="1.0.0"/>
        </restConfiguration>
        <rest path="/customer">
            <get uri="all">
            	<description>Retrieve all customer data</description>
                <to uri="direct:getallcustomer"/>
            </get>
        </rest>
      	<route id="customers">   <====== THIS
        <route id="customer">
            <from id="_from1" uri="timer:timer?repeatCount=1"/>
            <to id="_to1" uri="sql:select * from customerdemo?dataSource=dataSource"/>
            <log id="_log1" message="${body}"/>
        </route>
    </camelContext>

**Comment by weimeilin79** [comment]
Thanks! Fixed!
