### ISSUE TITLE
lab03 openshift view is not availble in the integration perspective

### ISSUE THREAD

**Issue by hguerrero** [jbossdemocentral/fuse-introlab#14]
in lab03 we are asked to add a new project using the openshift view, but that view is not available by default in the Fuse integration perspective, it is available in the JBoss one.

**Comment by weimeilin79** [comment]
This step is mention in the prerequisite lab. :)

**Comment by hguerrero** [comment]
In lab03 is referenced for creating the new project and deploying the mysql database, but user is moved to fuse integration perspective, just to add they will need to go back again to the jboss perspetive 

![screenshot from 2017-07-24 20-52-06](https://user-images.githubusercontent.com/1001939/28552141-446c0e30-70b2-11e7-9d83-09f78675076a.png)

**Comment by weimeilin79** [comment]
I see. Added instruction to go to the openshift explorer without going back to jboss view
