### ISSUE TITLE
lab03 - curl test of created route points to incorrect url

### ISSUE THREAD

**Issue by hguerrero** [jbossdemocentral/fuse-introlab#17]
the route created for the services is harcoded to the cdkv2 suffix, better to take the new **hostname** from the same service page

![screenshot from 2017-07-24 20-39-46](https://user-images.githubusercontent.com/1001939/28551865-44ea4a18-70b0-11e7-8121-6052b0b3507f.png)

**Comment by weimeilin79** [comment]
Thanks! Fixed it to point t the new created route :)
