### ISSUE TITLE
Issues/Missing instructions running Lab2

### ISSUE THREAD

**Issue by AndyYuen** [jbossdemocentral/fuse-introlab#5]
Again this is on my Windows 10 hybrid.

1.  Instructions missing in creating new methods and mapping rules for 3scale.

2. There is mention of Access Token for setting the secret but there is not instruction on how to get it. For people who are not familiar with 3scale, it is not apparent how to get it.

3. 'oc secret new-basicauth apicast-configuration-url-secret --password=https://<ACCESS_TOKEN>@<DOMAIN>-admin.3scale.net' did not work for me. It always fails. I have to use 'oc new-app -f https://raw.githubusercontent.com/3scale/apicast/master/openshift/apicast-template.yml' to make apicast deployed. The link was given to me by Tom Corcoran (3scale).

**Comment by hguerrero** [comment]
'oc secret new-basicauth apicast-configuration-url-secret --password=https://<ACCESS_TOKEN>@-admin.3scale.net' 

Only creates the secret you need to connect the self-managed apicast to the 3scale SaaS admin portal. The next step (oc new-app -f ... ) is the one that effectively creates the pods. 

@AndyYuen what is not working? Can you add some stacktrace?

**Comment by weimeilin79** [comment]
@AndyYuen Have you checked?

**Comment by AndyYuen** [comment]
It is not setting secret that did not work, it is "oc new-app -f https://raw.githubusercontent.com/3scale/3scale-amp-openshift-templates/2.0.0.GA-redhat-2/apicast-gateway/apicast.yml| that did not work trying to do that for a long time.  This problem only occurred while using minshift. Using the VM worked.

**Comment by hguerrero** [comment]
@AndyYuen Good is working in the VM, that will be the preferred way to go. To debug the problem with the minishift, do you have the logs or the screenshots of what was not working? I mean, weren't the pods created? Did they get stuck?

**Comment by hguerrero** [comment]
@AndyYuen BTW the link tom gave to you is the upstream (not supported) template. The official for enterprise product is the one under 3scale-amp-openshift-templates.
