### ISSUE TITLE
Issues in Lab3

### ISSUE THREAD

**Issue by AndyYuen** [jbossdemocentral/fuse-introlab#6]
I tried on both minishift and 'oc cluster up', creation of MySQL always fails with error:
Crash loop back off

--
---> 01:14:11     Processing MySQL configuration files ...
  | ---> 01:14:11     Initializing database ...
  | ---> 01:14:11     Running mysqld --initialize-insecure ...
  | 2017-07-07T01:14:12.036758Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
  | 2017-07-07T01:14:22.958689Z 0 [Warning] InnoDB: New log files created, LSN=45790
  | 2017-07-07T01:14:24.856577Z 0 [Warning] InnoDB: Creating foreign key constraint system tables.
  | 2017-07-07T01:14:25.809800Z 0 [Warning] No existing UUID has been found, so we assume that this is the first time that this server has been started. Generating a new UUID: 9e073cdb-62b1-11e7-87a8-0242ac110004.
  | 2017-07-07T01:14:26.266931Z 0 [Warning] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
  | 2017-07-07T01:14:56.259732Z 0 [Warning] CA certificate ca.pem is self signed.
  | 2017-07-07T01:15:02.680928Z 1 [Warning] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.

**Comment by AndyYuen** [comment]
and logs in the deploy pod:

--> Scaling mysql-1 to 1
--> Waiting up to 10m0s for pods in rc mysql-1 to become ready
error: update acceptor rejected mysql-1: pods for rc "mysql-1" took longer than 600 seconds to become ready

**Comment by weimeilin79** [comment]
It looks like the mysql is starting, but I don't see any error. Can you spin up an empty mysql in your empty openshift? Does that work?

**Comment by AndyYuen** [comment]
I used 'oc cluster up' on a MacBook with 16G and MySQL started up without problem! Windows problem? Or memory problem?

It is going to be troublesome during the lab when people use different platforms!!!

**Comment by weimeilin79** [comment]
Good feedback. Will try other Windows to replicated it

**Comment by hguerrero** [comment]
Have you checked the permissons on the storage permissions? 

| 2017-07-07T01:14:26.266931Z 0 [Warning] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.

maybe this line could be a hint?

**Comment by weimeilin79** [comment]
Will have the VM for all participants! Should not run into this prob
