### ISSUE TITLE
Problem with running Minishift on VirtualBox image

### ISSUE THREAD

**Issue by dsoffner** [jbossdemocentral/fuse-introlab#7]
When using the RHEL based VirtualBox image minishift can be installed, but when running "minishift start" I get the following error and starting minishift fails:

![screen shot 2017-07-12 at 11 05 20](https://user-images.githubusercontent.com/21097381/28097974-e0553d0a-66f6-11e7-86d4-62fed5b4e8b9.png)

**Comment by weimeilin79** [comment]
You can't run VM on top of VM. Will need to use oc-cluster up
