### ISSUE TITLE
Installation of CDK on VirtualBox image fails

### ISSUE THREAD

**Issue by dsoffner** [jbossdemocentral/fuse-introlab#8]
Followed the following installation guide to install CDK on RHEL:
https://access.redhat.com/documentation/en-us/red_hat_container_development_kit/3.0/html-single/installation_guide/

Installation fails at step
$ minishift setup-cdk --force --default-vm-driver="kvm"

with the error:
![screen shot 2017-07-12 at 15 14 21](https://user-images.githubusercontent.com/21097381/28102774-db29d444-6714-11e7-8a8b-440da67d6274.png)

**Comment by weimeilin79** [comment]
Hugo did a great job in this article of how to install minishift. 
Try follow this one

https://developers.redhat.com/blog/2017/05/22/how-to-setup-a-3scale-amp-on-premise-all-in-one-install/

**Comment by hguerrero** [comment]
you can not install the CDK in the VirtualBox image as minishift creates a new VM (virtualization inside virtualization) something is not currently recommended (afaik it's not even supported) so the way to start the cluster is using the oc-cluster wrapper documented in the link Christina commented before.
